// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4rYFlrT72Y86rSmY6QbQzV8_eRgiR1og',
    appId: '1:840331226482:android:d98466a61ff55e0a65c1eb',
    messagingSenderId: '840331226482',
    projectId: 'fir-kullanim-33580',
    databaseURL: 'https://fir-kullanim-33580-default-rtdb.firebaseio.com',
    storageBucket: 'fir-kullanim-33580.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjBIoWtCvQPZ61whfEYozj8VeNQ-J_erc',
    appId: '1:840331226482:ios:73e331cd6cd8044065c1eb',
    messagingSenderId: '840331226482',
    projectId: 'fir-kullanim-33580',
    databaseURL: 'https://fir-kullanim-33580-default-rtdb.firebaseio.com',
    storageBucket: 'fir-kullanim-33580.appspot.com',
    androidClientId: '840331226482-0ratqurf31h44olim11v5av06k1q4ejk.apps.googleusercontent.com',
    iosClientId: '840331226482-r4qmbj2ki5c8c8ao7a5jegbs277l7r9m.apps.googleusercontent.com',
    iosBundleId: 'com.example.mascot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUfjNl4uvBOVPTAf1wkT1RmtqgHcxmvWA',
    appId: '1:840331226482:web:97c51398b1584b8265c1eb',
    messagingSenderId: '840331226482',
    projectId: 'fir-kullanim-33580',
    authDomain: 'fir-kullanim-33580.firebaseapp.com',
    databaseURL: 'https://fir-kullanim-33580-default-rtdb.firebaseio.com',
    storageBucket: 'fir-kullanim-33580.appspot.com',
    measurementId: 'G-MVKX0Y9CX9',
  );

}