// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUfjNl4uvBOVPTAf1wkT1RmtqgHcxmvWA',
    appId: '1:840331226482:web:85309f3d042e07c565c1eb',
    messagingSenderId: '840331226482',
    projectId: 'fir-kullanim-33580',
    authDomain: 'fir-kullanim-33580.firebaseapp.com',
    databaseURL: 'https://fir-kullanim-33580-default-rtdb.firebaseio.com',
    storageBucket: 'fir-kullanim-33580.appspot.com',
    measurementId: 'G-VHZBY3QLM6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4rYFlrT72Y86rSmY6QbQzV8_eRgiR1og',
    appId: '1:840331226482:android:80c027f05db7235e65c1eb',
    messagingSenderId: '840331226482',
    projectId: 'fir-kullanim-33580',
    databaseURL: 'https://fir-kullanim-33580-default-rtdb.firebaseio.com',
    storageBucket: 'fir-kullanim-33580.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjBIoWtCvQPZ61whfEYozj8VeNQ-J_erc',
    appId: '1:840331226482:ios:895a4b5bce3edc6365c1eb',
    messagingSenderId: '840331226482',
    projectId: 'fir-kullanim-33580',
    databaseURL: 'https://fir-kullanim-33580-default-rtdb.firebaseio.com',
    storageBucket: 'fir-kullanim-33580.appspot.com',
    androidClientId: '840331226482-0ratqurf31h44olim11v5av06k1q4ejk.apps.googleusercontent.com',
    iosClientId: '840331226482-dmvatb9tinnqnlian1sq8ca52k8p3qrg.apps.googleusercontent.com',
    iosBundleId: 'com.example.bananatree',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjBIoWtCvQPZ61whfEYozj8VeNQ-J_erc',
    appId: '1:840331226482:ios:895a4b5bce3edc6365c1eb',
    messagingSenderId: '840331226482',
    projectId: 'fir-kullanim-33580',
    databaseURL: 'https://fir-kullanim-33580-default-rtdb.firebaseio.com',
    storageBucket: 'fir-kullanim-33580.appspot.com',
    androidClientId: '840331226482-0ratqurf31h44olim11v5av06k1q4ejk.apps.googleusercontent.com',
    iosClientId: '840331226482-dmvatb9tinnqnlian1sq8ca52k8p3qrg.apps.googleusercontent.com',
    iosBundleId: 'com.example.bananatree',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUfjNl4uvBOVPTAf1wkT1RmtqgHcxmvWA',
    appId: '1:840331226482:web:f2ee0a14def507e765c1eb',
    messagingSenderId: '840331226482',
    projectId: 'fir-kullanim-33580',
    authDomain: 'fir-kullanim-33580.firebaseapp.com',
    databaseURL: 'https://fir-kullanim-33580-default-rtdb.firebaseio.com',
    storageBucket: 'fir-kullanim-33580.appspot.com',
    measurementId: 'G-DDPV0162RN',
  );
}
